version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: cynical_circle_db
    environment:
      POSTGRES_DB: cynical_circle
      POSTGRES_USER: cynical_app
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/init.sql:/docker-entrypoint-initdb.d/02_init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cynical_app -d cynical_circle"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cynical_network

  # FastAPI приложение
  api:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cynical_circle_api
    environment:
      DATABASE_URL: postgresql://cynical_app:secure_password_123@postgres:5432/cynical_circle
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: "False"
      SECRET_KEY: your-secret-key-change-this
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cynical_network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: cynical_circle_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - cynical_network

  # pgAdmin для управления БД (опционально)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cynical_circle_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cynical.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - cynical_network

volumes:
  postgres_data:
    driver: local

networks:
  cynical_network:
    driver: bridge
